### ISSUE TITLE
NonLocal and Flow consistency threshold disabled

### ISSUE THREAD

**Issue by donglao** [vt-vl-lab/FGVC#37]
Greetings! Thanks for sharing your impressive work.

I was trying to find the non-local flow computation and forward-backward flow consistency check in your code. But it seems that the 'NonLocal' option is disabled by default and the 'consistencyThres' is set to inf which means it won't filter out any outliers. The results still seem reasonable, though. Could you please verify if my interpretation is correct and give me some guidance on how to tune these parameters?

Cheers,
Lao

**Comment by gaochen315** [comment]
Currently, I disable the usage of the non-local flow for a faster speed. But I do provide the non-local implementation in `get_flowNN.py` so it should be easy to use.

Your interpretation in consistencyThres is correct. If we are too strict with it, the algorithm will prefer the per-frame inpainted content to the propagated content, tho the quality may not be very good. If the constraint is too loose (inf), the algorithm will propagate everything. The result is smooth but probably incorrect.

If you really care about the correctness, I'll suggest using consistencyThres=5. The reason I set the default to be inf is that

1> it speeds up the process, and 
2> our seamless blending will make sure to smoothen the propagated content so that the final result is plausible (even though it is not correct).

Hope this helps!

**Comment by donglao** [comment]
Thanks! Your answer really helps!

**Comment by donglao** [comment]
One more question, please. Is the same set of parameters recommended for the fixed region removal task， too?

**Comment by gaochen315** [comment]
Yep, I use the same set of parameters.

You can always start with consistencyThres=5 and then adjust. If you enable seamless blending, I'll suggest using a looser threshold, i.e. 99.

Sorry for the late reply. Let me know if you have other questions.

**Comment by gao123qiang** [comment]
@gaochen315 
if the mask part is small, the consistencyThres will be small ?
