### ISSUE TITLE
The implementation of the homography warp before optical flow calculation

### ISSUE THREAD

**Issue by veizgyauzgyauz** [vt-vl-lab/FGVC#55]
Thanks for sharing such a great job! As said in the paper, a homography warp, which is estimated using RANSAC on ORB feature matches, is used before calculating the optical flow. I'm wondering where the implementation of this operation locates since I can't find it in the code.

**Comment by brunomsantiago** [comment]
I am not part of the project but I've read the code a few times. The best function to follow what happens under the hood is [video_completion_seamless on video_completion.py](https://github.com/vt-vl-lab/FGVC/blob/6b9826162f290adc5bae8c04b196eb5c4b24ee12/tool/video_completion.py#L380).

In this function the first thing they do with the frames is calculating the flow, so they probably meant "before using the optical flow" instead of "before calculating the optical flow". There is a part of this same function where they calculate some gradients (see line 468 to line 492 of video_completion.py). I don't know much about RANSAC or ORB, but it seems to be feature matching.

**Comment by veizgyauzgyauz** [comment]
Thanks for your reply! I've checked the lines you pointed out. But it seems that the author just applies `cv2.inpaint` for video frame inpainting and calculates gradients of the inpainted frames. The gradients are used for temporal neighbor fusing in Sec. 3.4. I guess the author inpaints the video frames first because it contributes to getting better gradients. But those operations have nothing to do with estimating an aligning homography matrix using RANSAC.

**Comment by kpbhat25** [comment]
if i know the optical flow between two images , can i estimate the homography warp ?
